// Generated by `supabase gen types typescript` — do not edit manually.
// Regenerate after migrations: supabase gen types typescript > types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          after_state: Json | null
          before_state: Json | null
          created_at: string
          id: string
          property_id: string | null
          resource_id: string | null
          resource_type: string
          user_id: string
        }
        Insert: {
          action: string
          after_state?: Json | null
          before_state?: Json | null
          created_at?: string
          id?: string
          property_id?: string | null
          resource_id?: string | null
          resource_type: string
          user_id: string
        }
        Update: {
          action?: string
          after_state?: Json | null
          before_state?: Json | null
          created_at?: string
          id?: string
          property_id?: string | null
          resource_id?: string | null
          resource_type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      calendar_blocks: {
        Row: {
          block_type: Database["public"]["Enums"]["calendar_block_type"]
          created_at: string
          created_by: string | null
          end_date: string
          id: string
          is_public: boolean
          organization_id: string
          property_id: string
          reason: string | null
          reservation_id: string | null
          start_date: string
          updated_at: string
        }
        Insert: {
          block_type?: Database["public"]["Enums"]["calendar_block_type"]
          created_at?: string
          created_by?: string | null
          end_date: string
          id?: string
          is_public?: boolean
          organization_id: string
          property_id: string
          reason?: string | null
          reservation_id?: string | null
          start_date: string
          updated_at?: string
        }
        Update: {
          block_type?: Database["public"]["Enums"]["calendar_block_type"]
          created_at?: string
          created_by?: string | null
          end_date?: string
          id?: string
          is_public?: boolean
          organization_id?: string
          property_id?: string
          reason?: string | null
          reservation_id?: string | null
          start_date?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "calendar_blocks_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "calendar_blocks_reservation_id_fkey"
            columns: ["reservation_id"]
            isOneToOne: false
            referencedRelation: "reservations"
            referencedColumns: ["id"]
          },
        ]
      }
      guests: {
        Row: {
          created_at: string
          email: string | null
          full_name: string
          id: string
          nationality: string | null
          notes: string | null
          organization_id: string
          phone: string | null
          tags: string[]
          updated_at: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          full_name: string
          id?: string
          nationality?: string | null
          notes?: string | null
          organization_id: string
          phone?: string | null
          tags?: string[]
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          full_name?: string
          id?: string
          nationality?: string | null
          notes?: string | null
          organization_id?: string
          phone?: string | null
          tags?: string[]
          updated_at?: string
        }
        Relationships: []
      }
      organization_members: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          role?: string
          user_id?: string
        }
        Relationships: []
      }
      properties: {
        Row: {
          address: string | null
          base_nightly_rate: number | null
          bathrooms: number | null
          bedrooms: number | null
          check_in_time: string | null
          check_out_time: string | null
          cleaning_fee_default: number | null
          created_at: string
          created_by: string
          description: string | null
          ical_token: string | null
          id: string
          max_guests: number | null
          name: string
          platform: string
          projections_config: Json | null
          slug: string
        }
        Insert: {
          address?: string | null
          base_nightly_rate?: number | null
          bathrooms?: number | null
          bedrooms?: number | null
          check_in_time?: string | null
          check_out_time?: string | null
          cleaning_fee_default?: number | null
          created_at?: string
          created_by: string
          description?: string | null
          ical_token?: string | null
          id?: string
          max_guests?: number | null
          name: string
          platform?: string
          projections_config?: Json | null
          slug: string
        }
        Update: {
          address?: string | null
          base_nightly_rate?: number | null
          bathrooms?: number | null
          bedrooms?: number | null
          check_in_time?: string | null
          check_out_time?: string | null
          cleaning_fee_default?: number | null
          created_at?: string
          created_by?: string
          description?: string | null
          ical_token?: string | null
          id?: string
          max_guests?: number | null
          name?: string
          platform?: string
          projections_config?: Json | null
          slug?: string
        }
        Relationships: []
      }
      property_access: {
        Row: {
          created_at: string
          granted_by: string
          id: string
          property_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          granted_by: string
          id?: string
          property_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          granted_by?: string
          id?: string
          property_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "property_access_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      property_finance_airbnb_rows: {
        Row: {
          airbnb_remitted_tax: number | null
          amount: number | null
          arriving_by_date: string | null
          booking_date: string | null
          cleaning_fee: number | null
          confirmation_code: string | null
          created_at: string
          created_by: string
          currency: string | null
          details: string | null
          earnings_year: string | null
          end_date: string | null
          fast_pay_fee: number | null
          gross_earnings: number | null
          guest: string | null
          guest_count: number | null
          id: string
          listing: string | null
          nights: number | null
          paid_out: number | null
          period_month: string
          property_id: string
          raw: Json | null
          reference_code: string | null
          row_date: string | null
          row_type: string | null
          service_fee: number | null
          start_date: string | null
        }
        Insert: {
          airbnb_remitted_tax?: number | null
          amount?: number | null
          arriving_by_date?: string | null
          booking_date?: string | null
          cleaning_fee?: number | null
          confirmation_code?: string | null
          created_at?: string
          created_by: string
          currency?: string | null
          details?: string | null
          earnings_year?: string | null
          end_date?: string | null
          fast_pay_fee?: number | null
          gross_earnings?: number | null
          guest?: string | null
          guest_count?: number | null
          id?: string
          listing?: string | null
          nights?: number | null
          paid_out?: number | null
          period_month: string
          property_id: string
          raw?: Json | null
          reference_code?: string | null
          row_date?: string | null
          row_type?: string | null
          service_fee?: number | null
          start_date?: string | null
        }
        Update: {
          airbnb_remitted_tax?: number | null
          amount?: number | null
          arriving_by_date?: string | null
          booking_date?: string | null
          cleaning_fee?: number | null
          confirmation_code?: string | null
          created_at?: string
          created_by?: string
          currency?: string | null
          details?: string | null
          earnings_year?: string | null
          end_date?: string | null
          fast_pay_fee?: number | null
          gross_earnings?: number | null
          guest?: string | null
          guest_count?: number | null
          id?: string
          listing?: string | null
          nights?: number | null
          paid_out?: number | null
          period_month?: string
          property_id?: string
          raw?: Json | null
          reference_code?: string | null
          row_date?: string | null
          row_type?: string | null
          service_fee?: number | null
          start_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "property_finance_airbnb_rows_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      property_finance_direct_bookings: {
        Row: {
          amount: number | null
          check_in: string | null
          check_out: string | null
          created_at: string
          created_by: string | null
          guest_count: number | null
          guest_name: string | null
          guest_phone: string | null
          id: string
          nights: number | null
          notes: string | null
          period_month: string
          property_id: string
          received_date: string | null
          reservation_id: string | null
          source: string | null
        }
        Insert: {
          amount?: number | null
          check_in?: string | null
          check_out?: string | null
          created_at?: string
          created_by?: string | null
          guest_count?: number | null
          guest_name?: string | null
          guest_phone?: string | null
          id?: string
          nights?: number | null
          notes?: string | null
          period_month: string
          property_id: string
          received_date?: string | null
          reservation_id?: string | null
          source?: string | null
        }
        Update: {
          amount?: number | null
          check_in?: string | null
          check_out?: string | null
          created_at?: string
          created_by?: string | null
          guest_count?: number | null
          guest_name?: string | null
          guest_phone?: string | null
          id?: string
          nights?: number | null
          notes?: string | null
          period_month?: string
          property_id?: string
          received_date?: string | null
          reservation_id?: string | null
          source?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "property_finance_direct_bookings_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "property_finance_direct_bookings_reservation_id_fkey"
            columns: ["reservation_id"]
            isOneToOne: false
            referencedRelation: "reservations"
            referencedColumns: ["id"]
          },
        ]
      }
      property_finance_expenses: {
        Row: {
          amount: number
          created_at: string
          created_by: string
          expense_date: string | null
          expense_type: string
          id: string
          notes: string | null
          owner_id: string | null
          paid_from: string
          period_month: string
          property_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          created_by: string
          expense_date?: string | null
          expense_type: string
          id?: string
          notes?: string | null
          owner_id?: string | null
          paid_from?: string
          period_month: string
          property_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          created_by?: string
          expense_date?: string | null
          expense_type?: string
          id?: string
          notes?: string | null
          owner_id?: string | null
          paid_from?: string
          period_month?: string
          property_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "property_finance_expenses_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "property_owners"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "property_finance_expenses_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      property_finance_loans: {
        Row: {
          annual_rate: number | null
          created_at: string
          created_by: string
          id: string
          name: string
          principal: number | null
          property_id: string
          start_date: string | null
          status: string
          tenure_months: number | null
        }
        Insert: {
          annual_rate?: number | null
          created_at?: string
          created_by: string
          id?: string
          name: string
          principal?: number | null
          property_id: string
          start_date?: string | null
          status?: string
          tenure_months?: number | null
        }
        Update: {
          annual_rate?: number | null
          created_at?: string
          created_by?: string
          id?: string
          name?: string
          principal?: number | null
          property_id?: string
          start_date?: string | null
          status?: string
          tenure_months?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "property_finance_loans_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      property_owners: {
        Row: {
          created_at: string
          id: string
          name: string
          property_id: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          property_id: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          property_id?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "property_owners_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      reservation_events: {
        Row: {
          actor_id: string | null
          event_type: string
          from_status: Database["public"]["Enums"]["reservation_status"] | null
          id: string
          metadata: Json | null
          notes: string | null
          occurred_at: string
          organization_id: string
          reservation_id: string
          to_status: Database["public"]["Enums"]["reservation_status"] | null
        }
        Insert: {
          actor_id?: string | null
          event_type: string
          from_status?: Database["public"]["Enums"]["reservation_status"] | null
          id?: string
          metadata?: Json | null
          notes?: string | null
          occurred_at?: string
          organization_id: string
          reservation_id: string
          to_status?: Database["public"]["Enums"]["reservation_status"] | null
        }
        Update: {
          actor_id?: string | null
          event_type?: string
          from_status?: Database["public"]["Enums"]["reservation_status"] | null
          id?: string
          metadata?: Json | null
          notes?: string | null
          occurred_at?: string
          organization_id?: string
          reservation_id?: string
          to_status?: Database["public"]["Enums"]["reservation_status"] | null
        }
        Relationships: [
          {
            foreignKeyName: "reservation_events_reservation_id_fkey"
            columns: ["reservation_id"]
            isOneToOne: false
            referencedRelation: "reservations"
            referencedColumns: ["id"]
          },
        ]
      }
      reservations: {
        Row: {
          adults: number
          channel: Database["public"]["Enums"]["reservation_channel"]
          check_in: string
          check_out: string
          children: number
          cleaning_fee: number
          created_at: string
          created_by: string | null
          deleted_at: string | null
          gross_revenue: number | null
          guest_email: string | null
          guest_id: string | null
          guest_name: string | null
          guest_phone: string | null
          id: string
          net_payout: number | null
          nightly_rate: number
          nights: number | null
          notes: string | null
          organization_id: string
          other_fees: number
          pets: number
          platform_booking_id: string | null
          platform_commission: number
          property_id: string
          raw_payload: Json | null
          status: Database["public"]["Enums"]["reservation_status"]
          taxes: number
          updated_at: string
        }
        Insert: {
          adults?: number
          channel?: Database["public"]["Enums"]["reservation_channel"]
          check_in: string
          check_out: string
          children?: number
          cleaning_fee?: number
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          gross_revenue?: number | null
          guest_email?: string | null
          guest_id?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          id?: string
          net_payout?: number | null
          nightly_rate?: number
          nights?: number | null
          notes?: string | null
          organization_id: string
          other_fees?: number
          pets?: number
          platform_booking_id?: string | null
          platform_commission?: number
          property_id: string
          raw_payload?: Json | null
          status?: Database["public"]["Enums"]["reservation_status"]
          taxes?: number
          updated_at?: string
        }
        Update: {
          adults?: number
          channel?: Database["public"]["Enums"]["reservation_channel"]
          check_in?: string
          check_out?: string
          children?: number
          cleaning_fee?: number
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          gross_revenue?: number | null
          guest_email?: string | null
          guest_id?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          id?: string
          net_payout?: number | null
          nightly_rate?: number
          nights?: number | null
          notes?: string | null
          organization_id?: string
          other_fees?: number
          pets?: number
          platform_booking_id?: string | null
          platform_commission?: number
          property_id?: string
          raw_payload?: Json | null
          status?: Database["public"]["Enums"]["reservation_status"]
          taxes?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reservations_guest_id_fk"
            columns: ["guest_id"]
            isOneToOne: false
            referencedRelation: "guests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reservations_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      seasonal_rates: {
        Row: {
          created_at: string
          end_date: string
          id: string
          is_active: boolean
          min_nights: number
          name: string
          nightly_rate: number
          organization_id: string
          property_id: string
          start_date: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          end_date: string
          id?: string
          is_active?: boolean
          min_nights?: number
          name: string
          nightly_rate: number
          organization_id: string
          property_id: string
          start_date: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          end_date?: string
          id?: string
          is_active?: boolean
          min_nights?: number
          name?: string
          nightly_rate?: number
          organization_id?: string
          property_id?: string
          start_date?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "seasonal_rates_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          created_at: string
          full_name: string | null
          id: string
          organization_id: string | null
          role: string
        }
        Insert: {
          created_at?: string
          full_name?: string | null
          id: string
          organization_id?: string | null
          role?: string
        }
        Update: {
          created_at?: string
          full_name?: string | null
          id?: string
          organization_id?: string | null
          role?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_current_user_org_id: { Args: never; Returns: string }
      is_new_signup: { Args: { p_user_id: string }; Returns: boolean }
    }
    Enums: {
      calendar_block_type:
        | "reservation"
        | "owner_hold"
        | "maintenance"
        | "buffer"
        | "seasonal_close"
      reservation_channel:
        | "airbnb"
        | "booking_com"
        | "direct"
        | "vrbo"
        | "expedia"
        | "other"
      reservation_status:
        | "inquiry"
        | "confirmed"
        | "checked_in"
        | "checked_out"
        | "cancelled"
        | "no_show"
        | "conflict"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      calendar_block_type: [
        "reservation",
        "owner_hold",
        "maintenance",
        "buffer",
        "seasonal_close",
      ],
      reservation_channel: [
        "airbnb",
        "booking_com",
        "direct",
        "vrbo",
        "expedia",
        "other",
      ],
      reservation_status: [
        "inquiry",
        "confirmed",
        "checked_in",
        "checked_out",
        "cancelled",
        "no_show",
        "conflict",
      ],
    },
  },
} as const
